// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRXbBjjTIybo2ot2LPGKNH4l2FB8n84pM',
    appId: '1:867251034015:web:de9700adb6b09062d00faa',
    messagingSenderId: '867251034015',
    projectId: 'smart-construction-hub',
    authDomain: 'smart-construction-hub.firebaseapp.com',
    storageBucket: 'smart-construction-hub.firebasestorage.app',
    measurementId: 'G-QF4MKP41L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmgHHCfN-yo_YkzCBfknQTNGIAeC_WnQc',
    appId: '1:867251034015:android:1d744cc7c22a5c83d00faa',
    messagingSenderId: '867251034015',
    projectId: 'smart-construction-hub',
    storageBucket: 'smart-construction-hub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY8kDr3KRQQqaW_-3eJixsNH2qF48v65A',
    appId: '1:867251034015:ios:95829d1f0aadec51d00faa',
    messagingSenderId: '867251034015',
    projectId: 'smart-construction-hub',
    storageBucket: 'smart-construction-hub.firebasestorage.app',
    iosBundleId: 'com.example.smartConstuctionHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY8kDr3KRQQqaW_-3eJixsNH2qF48v65A',
    appId: '1:867251034015:ios:95829d1f0aadec51d00faa',
    messagingSenderId: '867251034015',
    projectId: 'smart-construction-hub',
    storageBucket: 'smart-construction-hub.firebasestorage.app',
    iosBundleId: 'com.example.smartConstuctionHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRXbBjjTIybo2ot2LPGKNH4l2FB8n84pM',
    appId: '1:867251034015:web:f8557b7769ea2740d00faa',
    messagingSenderId: '867251034015',
    projectId: 'smart-construction-hub',
    authDomain: 'smart-construction-hub.firebaseapp.com',
    storageBucket: 'smart-construction-hub.firebasestorage.app',
    measurementId: 'G-CCYR7T6NL1',
  );
}
